```{r}
getwd()
setwd('C:/Users/Ashmeet/Desktop/Udacity/')
```


```{r}
ggplot(aes(x = price),data = diamonds) +
  facet_wrap( ~color) + geom_histogram(aes(fill = cut)) + scale_fill_brewer(type = 'qual')
```


```{r}
ggplot(aes(x = table, y = price),data = diamonds) +
  geom_point(aes(colour = cut)) + 
  scale_x_continuous(breaks = seq(50,80,2), limits   = c(50, 80))
+ 
  scale_fill_brewer(type = 'qual')
```


```{r}
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z

ggplot(aes(x = volume, y = price),data = diamonds) +
  geom_point(aes(colour = clarity)) + coord_trans(y = "log10") + 
  scale_fill_brewer(type = 'div') + 
  scale_x_continuous(breaks = seq(0,350,100), limits   = c(0, 350)) + 
  scale_y_continuous(breaks = seq(0,15000,1000), limits = c(0, 15000))
```


```{r}
getwd()
setwd('C:/Users/Ashmeet/Desktop/Udacity/')
library(ggplot2)
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')

```


```{r}
pf$prop_initiated <- pf$friendships_initiated/pf$friend_count
```


```{r}
ggplot(aes(x = tenure, y = prop_initiated),
       data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = mean) 
```


```{r}
ggplot(aes(x = tenure, y = prop_initiated),
       data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_smooth(aes(color = year_joined.bucket))
```


```{r}
ggplot(aes(x = cut, y = price/carat),data = diamonds) +
  geom_jitter(aes(colour = color)) + facet_wrap( ~clarity) +
  scale_x_continuous(breaks = seq(50,80,2), limits   = c(50, 80))
+ 
  scale_fill_brewer(type = 'div')
```

